### ISSUE TITLE
Show current line only with actual line number

### ISSUE THREAD

**Issue by jasjuang** [tmanderson/VintageLines#41]
Would be nice to replace 0 with the actual line number while the other lines remains the relative line number. Thanks!

**Comment by co-dh** [comment]
check https://github.com/co-dh/VintageLines

**Comment by jasjuang** [comment]
I just tried it but

1. 0 is replaced with a black box instead of the actual line number
2. When I switch to insert mode all the line number disappears

I am on Ubuntu 14.04 and Sublime Text 3

Thanks a lot for trying to make this happen

**Comment by co-dh** [comment]
If the current line > 99, it's a black box. I don't know how to fix this.
Do you need relative line number in insert mode? seemed make no sense for me.
If you need just line number in insert mode, toggle line number as this:
{"keys": ["ctrl+t"], "command": "toggle_setting", "args": {"setting": "line_numbers"}}

**Comment by jasjuang** [comment]
I mean the actual line number in insert mode just like what the original
vintage lines. I feel like it can potentially fits 4 numbers. With the
original vintage line if you switch back and forth between normal mode and
insert mode, there is actually still a lot of space for the gutter in
insert mode.

**Comment by co-dh** [comment]
Ok, I regenerate 0 to 999.png for linux and checked in. 
Now the current line is able to display up to 999. 
The font is ugly due to the size limit on icon, but it works.
do a git pull from my branch.

The relative line number is displayed with icon ( png), and I believe sublime will shrink them if it's too big.
I don't think sublime provide api to change line number.

**Comment by jasjuang** [comment]
This work well. I like that it won't jump anymore when switching between
insert mode and normal mode. Also it's very unlikely that my code will
exceed 1000 lines per file.

My problem is still can't figure out how to get the normal line number to
show in insert mode. I tried adding "line_numbers":true to
Preferences.sublime-settings but it did nothing. I also tried adding
your "keys":
["ctrl+t"], "command": "toggle_setting", "args": {"setting":
"line_numbers"} to Preferences.sublime-settings but also nothing happens.
Could you clarify more on what to do in order to enable line number in
normal mode?

**Comment by co-dh** [comment]
the keys should in Preference /Key binding - Users, instead of sublime-settings.
It's in Default(Lnux).sublime-keymap.

This plugin modify line_numbers in setting, so set it to true will be override.

**Comment by jasjuang** [comment]
This works but I will have to type ctrl + t to enable it. Is it possible to
enable it by default?

**Comment by co-dh** [comment]
It's more personal taste on whether enable by default.
I may not work on it.

**Comment by jasjuang** [comment]
I just realized another minor problem. The line number that is shown should be increased by 1, meaning it should start the count at one instead of zero. 

For example, open a random file and type "3gg", the line number on the left will show

2
1
2
1
2
3
4

and so on .. I would expect it to be 


2
1
3
1
2
3
4

**Comment by binarious** [comment]
@co-dh So you're now maintaining the project? Great, thanks for your effort! :+1: 
Shouldn't the issues be transfered to your repository?
Could you please take a look at https://github.com/tmanderson/VintageLines/issues/37 which unfortunately makes this plugin pretty much unusable.
(Sorry for misusing this issue for a mention.)

**Comment by jasjuang** [comment]
this is actually working properly already
